[package]
name = "midilang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.16", features = ["derive"] }
midly = "0.5.2"
log = "0.4"
env_logger = "0.9"
